services:
  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    depends_on:
      valkey :
        condition: service_healthy


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    depends_on:
      valkey :
        condition: service_healthy
    command: ["node", "worker.js"]